

name: Deploy To Render
on:
  push:
    branches:
      - main
jobs:
  deploy-to-render:
    name: Deploy To Render
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v4
      # Step 2: Install dependencies (optional if deployment doesn't require this)
      - name: Install Dependencies
        run: |
          npm ci
      # Step 3: Deploy to Render
      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST "$deploy_url"